/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MeuPrimeiroProjeto;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        System.out.println("Hello World by Geova");
        System.out.println("Cheguei no Java");
        //comentario em linha
        /*
        Primeira linha de comentário
        */
    }
}
